# Generated by Django 5.2.5 on 2025-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_profile_image_url',
            field=models.TextField(blank=True),
        ),
    ]
