# Generated by Django 5.2.5 on 2025-08-29 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_management', '0003_organization_members_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='organizations_administratorship', to=settings.AUTH_USER_MODEL),
        ),
    ]
