# Generated by Django 5.2.5 on 2025-09-11 02:57

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', files.models.PrefixedIDField(max_length=255, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('filetype', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=50)),
                ('bucket', models.CharField(max_length=255)),
                ('location', models.TextField()),
            ],
        ),
    ]
