# Generated by Django 5.2.5 on 2025-12-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('organizations_management', '0004_organization_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filetype',
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(choices=[('application/pdf', 'Adobe PDF (.pdf)'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Microsoft Word (.docx)'), ('text/plain', 'Plain Text (.txt)'), ('text/csv', 'Comma Separated Values (.csv)'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Microsoft Excel (.xlsx)'), ('image/jpeg', 'JPEG Image (.jpg/.jpeg)'), ('image/png', 'Portable Network Graphics (.png)'), ('image/gif', 'Graphics Interchange Format (.gif)'), ('image/svg+xml', 'Scalable Vector Graphics (.svg)'), ('image/webp', 'WebP Image (.webp)'), ('video/mp4', 'MPEG-4 Video (.mp4)'), ('audio/mpeg', 'MPEG-3 Audio (.mp3)'), ('audio/wav', 'Waveform Audio (.wav)'), ('application/zip', 'Zip Compressed Archive (.zip)'), ('application/gzip', 'Gzip Archive (.gz)'), ('text/html', 'HyperText Markup Language (.html)'), ('application/json', 'JavaScript Object Notation (.json)'), ('application/xml', 'Extensible Markup Language (.xml)')], default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations_management.organization'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
